spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/web
    username: beyond
    password: "{cipher}2f877193c94b18588b1c5dbfec7b3d44e819034e2488b145d67b0a8c8c609504"
mybatis:
  type-aliases-package: com.beyond.subject.vo
  mapper-locations:
  - classpath:mappers/**/*.xml
springdoc:
  swagger-ui:
    operations-sorter: method
  paths-to-match:
  - /v1/**
department-service:
  # base-url: http://localhost:8080/v1/department-service/departments/
  # base-url: http://department-service/v1/department-service/departments/
  base-url: http://gateway-server/department/v1/department-service/departments/
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalue-zone: http://localhost:8761/eureka/

