server:
  port: 8761
eureka:
  instance:
    # 유레카 인스턴스에 호스트 이름을 설정한다.
    hostname: localhost
  client:
    # 컨피그 서버가 유레카 서비스에 등록되지 않도록 한다.
    register-with-eureka: false
    # 컨피그 서버가 캐시 레지스트리 정보를 로컬에 캐시하지 않도록 지시한다.
    fetch-registry: false
    # 서비스 URL을 제공한다.
    service-url: 
      defalut-zone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
